//! Serpent S-boxes, translated mechanically from
//! `Compression/_Encryption/ciphers/serpent.c`.
//!
//! GENERATED by `rust/cryptref/gen_serpent_sboxes.py` -- do not edit by hand.
//!
//! Each `sbN`/`ibN` macro there is a straight-line, single-assignment sequence
//! of `^ & | ~` over 32-bit words, so the conversion is literal: `~` becomes
//! `!`, each temporary becomes a `let`, and the four outputs come back as a
//! tuple.
//!
//! DArc's Serpent IS standard Serpent. It only appears not to be when built
//! for a non-x86_64 LP64 target, where tomcrypt_macros.h types `ulong32` as
//! `unsigned long` -- 64 bits -- and serpent.c's key expansion rotates with a
//! raw `(lk << 11) | (lk >> 21)` that is only a rotate at 32 bits. See
//! darc-crypto/tests/serpent_vectors.rs.
#![allow(clippy::many_single_char_names)]

#[inline(always)]
pub fn sb0(a: u32, b: u32, c: u32, d: u32) -> (u32, u32, u32, u32) {
    let t1 = a ^ d;
    let t2 = a & d;
    let t3 = c ^ t1;
    let t6 = b & t1;
    let t4 = b ^ t3;
    let t10 = !t3;
    let h = t2 ^ t4;
    let t7 = a ^ t6;
    let t14 = !t7;
    let t8 = c | t7;
    let t11 = t3 ^ t7;
    let g = t4 ^ t8;
    let t12 = h & t11;
    let f = t10 ^ t12;
    let e = t12 ^ t14;
    (e, f, g, h)
}

#[inline(always)]
pub fn ib0(a: u32, b: u32, c: u32, d: u32) -> (u32, u32, u32, u32) {
    let t1 = !a;
    let t2 = a ^ b;
    let t3 = t1 | t2;
    let t4 = d ^ t3;
    let t7 = d & t2;
    let t5 = c ^ t4;
    let t8 = t1 ^ t7;
    let g = t2 ^ t5;
    let t11 = a & t4;
    let t9 = g & t8;
    let t14 = t5 ^ t8;
    let f = t4 ^ t9;
    let t12 = t5 | f;
    let h = t11 ^ t12;
    let e = h ^ t14;
    (e, f, g, h)
}

#[inline(always)]
pub fn sb1(a: u32, b: u32, c: u32, d: u32) -> (u32, u32, u32, u32) {
    let t1 = !a;
    let t2 = b ^ t1;
    let t3 = a | t2;
    let t4 = d | t2;
    let t5 = c ^ t3;
    let g = d ^ t5;
    let t7 = b ^ t4;
    let t8 = t2 ^ g;
    let t9 = t5 & t7;
    let h = t8 ^ t9;
    let t11 = t5 ^ t7;
    let f = h ^ t11;
    let t13 = t8 & t11;
    let e = t5 ^ t13;
    (e, f, g, h)
}

#[inline(always)]
pub fn ib1(a: u32, b: u32, c: u32, d: u32) -> (u32, u32, u32, u32) {
    let t1 = a ^ d;
    let t2 = a & b;
    let t3 = b ^ c;
    let t4 = a ^ t3;
    let t5 = b | d;
    let t7 = c | t1;
    let h = t4 ^ t5;
    let t8 = b ^ t7;
    let t11 = !t2;
    let t9 = t4 & t8;
    let f = t1 ^ t9;
    let t13 = t9 ^ t11;
    let t12 = h & f;
    let g = t12 ^ t13;
    let t15 = a & d;
    let t16 = c ^ t13;
    let e = t15 ^ t16;
    (e, f, g, h)
}

#[inline(always)]
pub fn sb2(a: u32, b: u32, c: u32, d: u32) -> (u32, u32, u32, u32) {
    let t1 = !a;
    let t2 = b ^ d;
    let t3 = c & t1;
    let t13 = d | t1;
    let e = t2 ^ t3;
    let t5 = c ^ t1;
    let t6 = c ^ e;
    let t7 = b & t6;
    let t10 = e | t5;
    let h = t5 ^ t7;
    let t9 = d | t7;
    let t11 = t9 & t10;
    let t14 = t2 ^ h;
    let g = a ^ t11;
    let t15 = g ^ t13;
    let f = t14 ^ t15;
    (e, f, g, h)
}

#[inline(always)]
pub fn ib2(a: u32, b: u32, c: u32, d: u32) -> (u32, u32, u32, u32) {
    let t1 = b ^ d;
    let t2 = !t1;
    let t3 = a ^ c;
    let t4 = c ^ t1;
    let t7 = a | t2;
    let t5 = b & t4;
    let t8 = d ^ t7;
    let t11 = !t4;
    let e = t3 ^ t5;
    let t9 = t3 | t8;
    let t14 = d & t11;
    let h = t1 ^ t9;
    let t12 = e | h;
    let f = t11 ^ t12;
    let t15 = t3 ^ t12;
    let g = t14 ^ t15;
    (e, f, g, h)
}

#[inline(always)]
pub fn sb3(a: u32, b: u32, c: u32, d: u32) -> (u32, u32, u32, u32) {
    let t1 = a ^ c;
    let t2 = d ^ t1;
    let t3 = a & t2;
    let t4 = d ^ t3;
    let t5 = b & t4;
    let g = t2 ^ t5;
    let t7 = a | g;
    let t8 = b | d;
    let t11 = a | d;
    let t9 = t4 & t7;
    let f = t8 ^ t9;
    let t12 = b ^ t11;
    let t13 = g ^ t9;
    let t15 = t3 ^ t8;
    let h = t12 ^ t13;
    let t16 = c & t15;
    let e = t12 ^ t16;
    (e, f, g, h)
}

#[inline(always)]
pub fn ib3(a: u32, b: u32, c: u32, d: u32) -> (u32, u32, u32, u32) {
    let t1 = b ^ c;
    let t2 = b | c;
    let t3 = a ^ c;
    let t7 = a ^ d;
    let t4 = t2 ^ t3;
    let t5 = d | t4;
    let t9 = t2 ^ t7;
    let e = t1 ^ t5;
    let t8 = t1 | t5;
    let t11 = a & t4;
    let g = t8 ^ t9;
    let t12 = e | t9;
    let f = t11 ^ t12;
    let t14 = a & g;
    let t15 = t2 ^ t14;
    let t16 = e & t15;
    let h = t4 ^ t16;
    (e, f, g, h)
}

#[inline(always)]
pub fn sb4(a: u32, b: u32, c: u32, d: u32) -> (u32, u32, u32, u32) {
    let t1 = a ^ d;
    let t2 = d & t1;
    let t3 = c ^ t2;
    let t4 = b | t3;
    let h = t1 ^ t4;
    let t6 = !b;
    let t7 = t1 | t6;
    let e = t3 ^ t7;
    let t9 = a & e;
    let t10 = t1 ^ t6;
    let t11 = t4 & t10;
    let g = t9 ^ t11;
    let t13 = a ^ t3;
    let t14 = t10 & g;
    let f = t13 ^ t14;
    (e, f, g, h)
}

#[inline(always)]
pub fn ib4(a: u32, b: u32, c: u32, d: u32) -> (u32, u32, u32, u32) {
    let t1 = c ^ d;
    let t2 = c | d;
    let t3 = b ^ t2;
    let t4 = a & t3;
    let f = t1 ^ t4;
    let t6 = a ^ d;
    let t7 = b | d;
    let t8 = t6 & t7;
    let h = t3 ^ t8;
    let t10 = !a;
    let t11 = c ^ h;
    let t12 = t10 | t11;
    let e = t3 ^ t12;
    let t14 = c | t4;
    let t15 = t7 ^ t14;
    let t16 = h | t10;
    let g = t15 ^ t16;
    (e, f, g, h)
}

#[inline(always)]
pub fn sb5(a: u32, b: u32, c: u32, d: u32) -> (u32, u32, u32, u32) {
    let t1 = !a;
    let t2 = a ^ b;
    let t3 = a ^ d;
    let t4 = c ^ t1;
    let t5 = t2 | t3;
    let e = t4 ^ t5;
    let t7 = d & e;
    let t8 = t2 ^ e;
    let t10 = t1 | e;
    let f = t7 ^ t8;
    let t11 = t2 | t7;
    let t12 = t3 ^ t10;
    let t14 = b ^ t7;
    let g = t11 ^ t12;
    let t15 = f & t12;
    let h = t14 ^ t15;
    (e, f, g, h)
}

#[inline(always)]
pub fn ib5(a: u32, b: u32, c: u32, d: u32) -> (u32, u32, u32, u32) {
    let t1 = !c;
    let t2 = b & t1;
    let t3 = d ^ t2;
    let t4 = a & t3;
    let t5 = b ^ t1;
    let h = t4 ^ t5;
    let t7 = b | h;
    let t8 = a & t7;
    let f = t3 ^ t8;
    let t10 = a | d;
    let t11 = t1 ^ t7;
    let e = t10 ^ t11;
    let t13 = a ^ c;
    let t14 = b & t10;
    let t15 = t4 | t13;
    let g = t14 ^ t15;
    (e, f, g, h)
}

#[inline(always)]
pub fn sb6(a: u32, b: u32, c: u32, d: u32) -> (u32, u32, u32, u32) {
    let t1 = !a;
    let t2 = a ^ d;
    let t3 = b ^ t2;
    let t4 = t1 | t2;
    let t5 = c ^ t4;
    let f = b ^ t5;
    let t13 = !t5;
    let t7 = t2 | f;
    let t8 = d ^ t7;
    let t9 = t5 & t8;
    let g = t3 ^ t9;
    let t11 = t5 ^ t8;
    let e = g ^ t11;
    let t14 = t3 & t11;
    let h = t13 ^ t14;
    (e, f, g, h)
}

#[inline(always)]
pub fn ib6(a: u32, b: u32, c: u32, d: u32) -> (u32, u32, u32, u32) {
    let t1 = !a;
    let t2 = a ^ b;
    let t3 = c ^ t2;
    let t4 = c | t1;
    let t5 = d ^ t4;
    let t13 = d & t1;
    let f = t3 ^ t5;
    let t7 = t3 & t5;
    let t8 = t2 ^ t7;
    let t9 = b | t8;
    let h = t5 ^ t9;
    let t11 = b | h;
    let e = t8 ^ t11;
    let t14 = t3 ^ t11;
    let g = t13 ^ t14;
    (e, f, g, h)
}

#[inline(always)]
pub fn sb7(a: u32, b: u32, c: u32, d: u32) -> (u32, u32, u32, u32) {
    let t1 = !c;
    let t2 = b ^ c;
    let t3 = b | t1;
    let t4 = d ^ t3;
    let t5 = a & t4;
    let t7 = a ^ d;
    let h = t2 ^ t5;
    let t8 = b ^ t5;
    let t9 = t2 | t8;
    let t11 = d & t3;
    let f = t7 ^ t9;
    let t12 = t5 ^ f;
    let t15 = t1 | t4;
    let t13 = h & t12;
    let g = t11 ^ t13;
    let t16 = t12 ^ g;
    let e = t15 ^ t16;
    (e, f, g, h)
}

#[inline(always)]
pub fn ib7(a: u32, b: u32, c: u32, d: u32) -> (u32, u32, u32, u32) {
    let t1 = a & b;
    let t2 = a | b;
    let t3 = c | t1;
    let t4 = d & t2;
    let h = t3 ^ t4;
    let t6 = !d;
    let t7 = b ^ t4;
    let t8 = h ^ t6;
    let t11 = c ^ t7;
    let t9 = t7 | t8;
    let f = a ^ t9;
    let t12 = d | f;
    let e = t11 ^ t12;
    let t14 = a & h;
    let t15 = t3 ^ f;
    let t16 = e ^ t14;
    let g = t15 ^ t16;
    (e, f, g, h)
}
