#!/usr/bin/env python3
"""Regenerate darc-crypto/src/serpent_sboxes.rs from the vendored serpent.c.

Run from the repository root:

    python3 rust/cryptref/gen_serpent_sboxes.py

The S-box macros are straight-line, single-assignment sequences of ^ & | ~ over
32-bit words, so the translation is literal. It is generated rather than typed
because 460 lines of bit-twiddling is where a transcription slip hides.

Two things this guards that a looser script would not:

  * C comments are stripped FIRST. serpent.c parks a second, slower sb3 inside
    a comment block; a regex running through it defines that S-box twice.
  * The macro count and uniqueness are asserted, so a future edit to serpent.c
    that adds or renames one fails here rather than silently producing a
    partial cipher.
"""
import re
import sys

SRC = "Compression/_Encryption/ciphers/serpent.c"
DST = "rust/darc-crypto/src/serpent_sboxes.rs"

HEADER = '''//! Serpent S-boxes, translated mechanically from
//! `Compression/_Encryption/ciphers/serpent.c`.
//!
//! GENERATED by `rust/cryptref/gen_serpent_sboxes.py` -- do not edit by hand.
//!
//! Each `sbN`/`ibN` macro there is a straight-line, single-assignment sequence
//! of `^ & | ~` over 32-bit words, so the conversion is literal: `~` becomes
//! `!`, each temporary becomes a `let`, and the four outputs come back as a
//! tuple.
//!
//! DArc's Serpent IS standard Serpent. It only appears not to be when built
//! for a non-x86_64 LP64 target, where tomcrypt_macros.h types `ulong32` as
//! `unsigned long` -- 64 bits -- and serpent.c's key expansion rotates with a
//! raw `(lk << 11) | (lk >> 21)` that is only a rotate at 32 bits. See
//! darc-crypto/tests/serpent_vectors.rs.
#![allow(clippy::many_single_char_names)]
'''


def main() -> int:
    src = open(SRC).read()
    stripped = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
    pat = re.compile(r"#define\s+((?:sb|ib)\d)\(([^)]*)\)\s*\\\n((?:.*\\\n)*.*)")

    names = [m.group(1) for m in pat.finditer(stripped)]
    if len(names) != len(set(names)):
        print(f"error: duplicate S-box after comment strip: {names}", file=sys.stderr)
        return 1
    if len(names) != 16:
        print(f"error: expected 16 S-boxes, found {len(names)}: {names}", file=sys.stderr)
        return 1

    out = [HEADER]
    for m in pat.finditer(stripped):
        name = m.group(1)
        params = [p.strip() for p in m.group(2).split(",")]
        ins, outs = params[:4], params[4:]
        stmts = [s.strip() for s in m.group(3).replace("\\\n", "\n").split(";") if s.strip()]

        seen = set()
        for s in stmts:
            lhs = s.split("=")[0].strip()
            if lhs in seen:
                print(f"error: {name} assigns {lhs} twice; not single-assignment", file=sys.stderr)
                return 1
            seen.add(lhs)

        lines = [
            "#[inline(always)]",
            f"pub fn {name}({ins[0]}: u32, {ins[1]}: u32, {ins[2]}: u32, {ins[3]}: u32)"
            " -> (u32, u32, u32, u32) {",
        ]
        for s in stmts:
            lhs, rhs = s.split("=", 1)
            lines.append(f"    let {lhs.strip()} = {rhs.strip().replace('~', '!')};")
        lines.append(f"    ({outs[0]}, {outs[1]}, {outs[2]}, {outs[3]})")
        lines.append("}\n")
        out.append("\n".join(lines))

    open(DST, "w").write("\n".join(out))
    print(f"wrote {DST}: {len(names)} S-boxes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
